#! /bin/bash

#####################################################################################
function info () { echo -e "\033[1;32m$@\033[0m"; }
function warn () { echo -e "\033[1;33m$@\033[0m"; }
function die  () { echo -e "\033[0;31m$*\033[0m"; exit 1; }
#####################################################################################

export DOCKER_IMAGE='linux-build-nanbield'
export DOCKER_USER=$(whoami)
export DOCKER_UUID=$(id -u)
export DOCKER_UGID=$(id -g)
export DOCKER_WORKDIR=$(pwd)
export DOCKER_PARAMS="--user ${DOCKER_USER} -v ${DOCKER_WORKDIR}:/home/${DOCKER_USER}/workspace:Z ${DOCKER_IMAGE}"

export PATH="${DOCKER_WORKDIR}/:${PATH}"
#####################################################################################

# find docker image and create if missing
find_image=$(docker images -q ${DOCKER_IMAGE})
if [ "${find_image}" = "" ]; then
	docker build --build-arg "DOCKER_UUID=${DOCKER_UUID}" --build-arg "DOCKER_UGID=${DOCKER_UGID}" --build-arg "DOCKER_USER=${DOCKER_USER}" -t ${DOCKER_IMAGE} docker
fi

#####################################################################################

# run docker with bb command
function bb.run() {
	docker run ${DOCKER_PARAMS} /home/exec.sh $@
}

export -f bb.run

#####################################################################################

# run docker with interactive shell and mounted local folder
function bb.exec() {
	docker run ${DOCKER_PARAMS} $@
}

export -f bb.exec

#####################################################################################

# run docker with interactive shell and mounted local folder
function bb.shell() {
	docker run -it ${DOCKER_PARAMS} /bin/bash
}

export -f bb.shell

#####################################################################################

# remove all stopped containers
function bb.purge() {
	find_stop=$(docker ps -aq)
	[ ! "${find_stop}" = "" ] && docker rm $(docker ps -aq)
}

export -f bb.purge

#####################################################################################

SUBMODULES="$(cat <<-EOF
f3ba9c3726ec7b38b557100d8a2d4b6a1446a968,layers/bitbake
941089fa63e2b38608291251d52a354f0f624926,layers/openembedded-core
3dd5d208be018f0f676d1adfceb9c22f19ad2ffe,layers/meta-openembedded
2e3ccdaf309a7271a47a1d95123b62bfd6294e9f,layers/meta-openrc
aca6d4a9e7c45cb44ac02062c2750cdfa1679cc6,layers/meta-security
ccddfb1f8b68cf9ab21bd416480f79d44a0a30f4,layers/meta-virtualization
482d864b8f1af84915ed6a9641e80af4e49a1f63,layers/meta-raspberrypi
EOF
)"

#####################################################################################

function init_submodules() {
	git submodule init
	git submodule update --recursive
}

#####################################################################################

function reset_submodules() {
	for submodule in ${SUBMODULES}; do
		IFS=',' read revision location <<< "${submodule}"
		info "RESET ${location} to REVISION ${revision}"

		pushd ${location} > /dev/null
			git clean -fxd ./    
			git reset --hard HEAD
			git checkout ${revision}
			
			local layer_patch=../${location#layers/}.patch
			[ -f ${layer_patch} ] && git apply ${layer_patch}
		popd > /dev/null
	done
}

#####################################################################################

init_submodules
reset_submodules

#####################################################################################
